config/routes.rb
Rails.application.routes.draw do
  get 'game/start_game', as: :start_game 
  get 'game/end_game'
  post 'game/make_step'
  get '/' => 'welcome#index'
  get 'profile' => 'users#profile_info'
  root 'users#profile_info'
  namespace :users do
    get 'omniauth_callbacks/vkontakte'
  end
  devise_for :users, 
    controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/game_steps_log.rb
class GameStepsLog < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:vkontakte]

  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.username = auth.info.first_name
        user.img_url = auth.info.image
        user.password = Devise.friendly_token[0,20]
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  
  def configure_permitted_parameters
    attributes = [:username, :nickname]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController

  before_action :require_user
  load Rails.root.join('lib/chess_game','chess.rb')

  def start_game
    
    # Remove this!!! STRONG
    Game.delete_all
    GameStepsLog.delete_all
    # END REMOVING

    game = Chess.new
    game.start_new_game
    session[:game_id] = game.game_id
    @current_step = game.whos_move
    @game_id = game.game_id
    @available_steps = game.available_steps
    @pieces_collection = game.pieces_collection
    @player_color = game.player_color
    @whos_move = game.whos_move
  end

  def continue_game
    p "we want continue game"
  end

  def make_step

    game = Chess.new
    response = game.get_current_game_state(params[:game_id])
    game.make_step(params)

    # here you need get available steps!!!


    render json: {
      available_steps: game.available_steps,
      current_step: game.whos_move,
      pieces_collection: game.pieces_collection
    }

  end

  def end_game
  end

  def require_user 
    redirect_to new_user_session_path, alert: "For game you need to login!" unless user_signed_in?

  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def vkontakte
    if request.env["omniauth.auth"].info.email.nil?
      flash[:notice] = "WTF?!?!?!? WE NEED YOU EMAIL"
      redirect_to root_path and return true
    else
      @user = User.from_omniauth(request.env["omniauth.auth"])
    end

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = "authentication error"
      redirect_to root_path
    end
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def profile_info
    if current_user.nil?
      redirect_to "/" and return 
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:username, :nickname, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/game/end_game.html.haml
%h1 Game#end_game
%p Find me in app/views/game/end_game.html.haml

app/views/game/start_game,.html.haml
%h1 Game#start_game,
%p Find me in app/views/game/start_game,.html.haml

app/views/game/start_game.html.haml
.chess_debug_info
  = #@available_steps.to_json
  = #@pieces_collection.to_json

.chess_field__wrapper
  = react_component("ChessField", { current_step: @current_step,
                    pieces_collection: @pieces_collection,
                    available_steps: @available_steps,
                    gameId: @game_id,
                    whosMove: @whos_move,
                    player_color: @player_color })
  =# react_component("ChessPieces", {pieces_collection: @pieces_collection})

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Authproviders"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application", 'data-turbolinks-track': 'reload'
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")
  %body
    .header
      %nav.navbar.navbar-inverse.navbar-static-top
        .container
          .navbar-header
            = link_to start_game_path, :class => "navbar-brand" do
              %span.glyphicon.glyphicon-tower
              Start Game
            = link_to root_path, :class => "navbar-brand" do
              My App
            %button.navbar-toggle.collapsed{"type"=>"button", "data-toggle"=>"collapse", "data-target"=>"#navbar6"}
              %span.sr-only
                Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
          #navbar6.navbar-collapse.collapse
            %ul.nav.navbar-nav.navbar-right
              %li
                %a.navbar-brand.avatar-link
                  - if !current_user || current_user.img_url.nil?
                    %span.glyphicon.glyphicon-user
                  - else
                    %img{src: current_user.img_url, width: '40px'}
              %li.dropdown
                %a.dropdown-toggle{"data-toggle"=>"dropdown", "role"=>"button", "aria-expanded"=>"false"}                  
                  - if current_user
                    = current_user.username
                  - else
                    Authorization
                  %span.caret
                %ul.dropdown-menu.account_menu{"role"=>"menu"}
                  - if current_user
                    %li
                      = link_to 'Log out', destroy_user_session_path, method: "delete"
                    %li
                      = link_to "Profile", controller: 'users', action: 'profile_info'
                  - else
                    %li
                      = link_to "Login", new_user_session_path
                    %li
                      = link_to "Signup", new_user_registration_path
              

    .container
      = render 'shared/flashes'
      .content
        .row
          .span9
            = yield
      %footer

app/views/shared/_flashes.html.haml
- flash.each do |key, message|
  %div{ class: key == 'alert' ?  'alert alert-danger' : 'alert alert-success', role: "alert" }
    %button.close{type: "button", "data-dismiss": "alert", "aria-label": "Close"}
      %span{"aria-hidden": "true"}
        &times;
    %p
      = message

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :nickname
    = f.text_field :nickname
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.text_field :password
  .field
    = f.label :password_confirmation
    = f.text_field :password_confirmation
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
- model_class = User.new.class
%h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:username)
      %th= model_class.human_attribute_name(:nickname)
      %th= model_class.human_attribute_name(:provider)
      %th= model_class.human_attribute_name(:sign_in_count)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.username, user.url
        %td= user.nickname
        %td= user.provider
        / %td= user.sign_in_count
        %td= user.created_at
        %td
          = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), :class => 'btn btn-mini btn-danger'

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/profile_info.html.haml
= p @current_user.to_json
%h1 Here you will see all information about your account

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @user.username
%p
  %b Nickname:
  = @user.nickname

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

app/views/welcome/index.html.haml
%h1 Good Day
%p Play Chess here